spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083

jwt:
  secret: uCaK3U0oisRXgekvMLOMrvzzZXfSlsdibnZ4cHNSaaA=
  accessTokenExpiration: 600000 # 10분 (1시간 = 60 * 60 * 1000)
  refreshTokenExpiration: 1800000   # 30분
