version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: trade-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: trade_db
      MYSQL_USER: trade_user
      MYSQL_PASSWORD: trade_pw
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: