
###회원가입
POST http://localhost:8080/v1/users/signup
Content-Type: application/json

{
  "user": {
    "userName": "tester",
    "nickName": "nick",
    "password": "1234",
    "email": "test@example.com",
    "profile": "https://profile.img"
  }
}
