server:
  port: 8086

spring:
  application:
    name: trade
  datasource:
    url: jdbc:mysql://localhost:3306/trade_db?serverTimezone=Asia/Seoul
    username: trade_user
    password: trade_pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/