spring:
  application:
    name: alert

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true


server:
  port: 8085


alert:
  service:
    url: "http://localhost:8085"


