version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-bookstore
    restart: always
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: